### ISSUE TITLE
VIEW field not working with values from other files

### ISSUE THREAD

**Issue by johanfriis** [mProjectsCode/obsidian-meta-bind-plugin#104]
-   [X] The Plugin is up to date
-   [X] Obsidian is up to date

**Describe the bug**

When trying to read a value from another file, the plugin shows the following error:

`[MB_EXPRESSION_ERROR] "failed to evaluate expression" caused by error "Undefined symbol MB_VAR_NOT_FOUND"`

**To Reproduce**

<img width="892" alt="Screenshot 2023-06-26 at 10 25 20" src="https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/3974347/526dad95-a903-475a-9e69-5f1a1d8c5668">

**Occurs on**

-   [ ] Windows
-   [X] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.5.1

**Comment by mProjectsCode** [comment]
fixed, i will release a new version with the fix later today

**Comment by SveBo29** [comment]
Is there a fixed version online? I still have the issue with the latest released version (0.5.1).

**Comment by mProjectsCode** [comment]
Ah i thought i put out a release with this fix before working on the new parser. 

Well the next release will be there in 1 to 2 weeks.
