### ISSUE TITLE
Example script 'Activity Tracker' doesn't work

### ISSUE THREAD

**Issue by simonfossom** [mProjectsCode/obsidian-meta-bind-plugin#167]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.10.2

### Describe the Issue

Example script 'Activity Tracker' trows error:

```
Failed to execute JS
Failed to execute JS during execution "6509f34a-6763-41f0-8df3-aced42ef130c"

Error: [MB_VALIDATION] "failed to validate parser result" caused by "Failed to parse bind target. Bind target storage path is undefined."

    at Pc.validateStoragePathAsFilePath (plugin:obsidian-meta-bind-plugin:49:9778)
    at Pc.validateBindTarget (plugin:obsidian-meta-bind-plugin:49:8229)
    at Pc.parseAndValidateBindTarget (plugin:obsidian-meta-bind-plugin:49:7853)
    at Am.createBindTarget (plugin:obsidian-meta-bind-plugin:102:2941)
    at qo.eval [as func] (eval at buildFunction (plugin:js-engine), <anonymous>:5:23)
    at qo.runFunction (plugin:js-engine:39:79271)
    at zo.execute (plugin:js-engine:39:84539)
    at Or.tryRun (plugin:js-engine:39:19287)
    at Or.renderResults (plugin:js-engine:39:19474)
    at Or.render (plugin:js-engine:39:20168)
```

### Steps to Reproduce

open the note from the link: https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/0213492d77966304668eb5429f50cc23808aa4f8/exampleVault/Advanced%20Examples/Activity%20Tracker.md

### Expected Behavior

Script should execute.

**Comment by mProjectsCode** [comment]
yeah, that is still using the old syntax. I will update this soon.

**Comment by mProjectsCode** [comment]
should be fixed now

**Comment by simonfossom** [comment]
@mProjectsCode sorry for late reaction but the problem persists in my vault. tried on clean vault same error.

![Screenshot 2024-01-07 at 22 59 04](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/8134850/0b7ddb70-0db3-490d-b5cb-fb1ce824741a)

**Comment by mProjectsCode** [comment]
Did you copy the example from the latest commit of the master branch? Because that version works for me without any problems.

**Comment by simonfossom** [comment]
1 sec

**Comment by LynetteCullens** [comment]
Activity Tracker and PF2e Encounter Calculator are not working in the example vault. All JavaScript codes are broken in the example vault.

**Comment by mProjectsCode** [comment]
I updated the example to use the new API. I also had to fix a few things in the plugin which I overlooked in the 1.0 release. I will release an update to the plugin possibly later today.
